package com.example.amovtp.utils.codes

enum class Codes {
    DEFAULT_VALUE,
    KEEP_VALUE,
    ALL_LOCATIONS,
    ALL_CATEGORIES,
    SUCCESS,
    ERROR_EXISTING_NAME,
    ERROR_EXISTING_POINT_OF_INTEREST,
    ERROR_EXISTING_LOCATION,
    ORDER_BY_VOTES,
    ORDER_BY_NAME,
    ORDER_BY_DISTANCE
}