package com.example.amovtp.utils.codes

enum class Codes {
    DEFAULT_VALUE,
    SUCCESS,
    ERROR_EXISTING_NAME,
    ERROR_EXISTING_LAT,
    ERROR_EXISTING_LONG,
    ERROR_EXISTING_POINT_OF_INTEREST,
    ERROR_EXISTING_LOCATION
}